### ISSUE TITLE
Bootloop issue

### ISSUE THREAD

**Issue by TTsdzb** [Nova-Kernels/kernel_xiaomi_mt6785#11]
A commit between `6381e4f30c7f9e3e30f0ff44a9d11ba4f33e77e1` and `0318283c523df741f4fd61a28e9b46c668a5845b` causes my device to bootloop. It only shows the very first "Redmi" screen, and then blank out with another boot, repeating this process.

I'm running MIUI 12.5.6.0.RGGCNXM. Compiled kernel before this commit works fine for me. However I don't know how to compile without `build.sh`, so I can't test out further.

I would like to help if you need more information.

**Comment by TTsdzb** [comment]
I can't compile the latest code due to #10, either.

**Comment by Wahid7852** [comment]
@TTsdzb I'd recommend you to join the TG Support group

**Comment by TTsdzb** [comment]
@Wahid7852 I'm already there. Guess I'll follow the TESTING channel?

**Comment by Wahid7852** [comment]
@TTsdzb Yes please tag me
